[package]
name = "Yet Another Block Game"
version = "0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = {path = "../meth" }